# Generated by Django 4.2.4 on 2023-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_default_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
