# Generated by Django 4.2.4 on 2023-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_orderlineitem_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
