# Generated by Django 4.2.4 on 2023-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_quantity',
            field=models.JSONField(default=dict),
        ),
    ]
